version: '3.7'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy -c cv-jenkins-buildslaves.yml servercv
# All services, networks, etc. will then get an "servercv_" prefix,
# eg. "servercv_centos7"

# Default slave configuration. This is written using a YAML anchor so
# it can be substituted into all the slave declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-default-jenkins-slave: &default-jenkins-slave
  deploy:
    replicas: 2
    update_config:
      parallelism: 1000
  networks:
    - jenkins
  sysctls:
    net.ipv6.conf.lo.disable_ipv6: 0

  secrets:
    - source: jenkins_master_username
    - source: jenkins_master_password
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profile_sync

x-default-jenkins-slave-environment:
 - &default-jenkins-slave-environment-master "JENKINS_MASTER=http://mega2.build.couchbase.com:8083/"

x-node-class:
 - &node-class "NODE_CLASS=cv"

x-node-product:
 - &node-product "NODE_PRODUCT=couchbase-server"

services:

  centos7_unit:
    image: couchbasebuild/server-centos7-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=unit-centos7"
      - "JENKINS_SLAVE_LABELS=centos7 unit-simple-test"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  ubuntu16_unit:
    image: couchbasebuild/server-ubuntu16-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=unit-ubuntu16"
      - "JENKINS_SLAVE_LABELS=ubuntu16.04 ubuntu16 unit-simple-test"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

configs:
  couchbase_ssh_config_20191031:
    file: conf/couchbase_ssh_config

secrets:
  jenkins_master_username:
    external: true
  jenkins_master_password:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true

networks:
  jenkins:
