---
- hosts: all
  gather_facts: no

  vars:
    ansible_user: couchbase
    ansible_password: couchbase
    ansible_become: true
    ansible_sudo_password: couchbase

  tasks:

    - name: Apt Update
      apt:
        update_cache: yes
        upgrade: dist

    - name: Disable automatic updates
      apt:
        name: unattended-upgrades
        state: absent
        purge: yes

    - name: See if apport is installed
      shell: dpkg-query -s apport
      ignore_errors: true
      register: apport_check
      changed_when: false

    - name: Disable apport
      systemd:
        name: apport
        enabled: no
      when: apport_check is succeeded

    - name: Enable coredumps in /tmp
      sysctl:
        name: kernel.core_pattern
        value: "/tmp/core.%e.%p.%h.%t"
        reload: yes
      tags: core
      changed_when: true

    - name: Reboot to get new kernel
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 5
      poll: 0

    - name: Wait for server to finish rebooting
      become: no
      connection: local
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 30
        timeout: 300

    - name: Clean unused packages
      apt:
        update_cache: yes
        autoremove: yes
        purge: yes

    - name: Get kernel version
      shell: uname -r
      register: uname
      changed_when: false

    - name: Install additional packages for Docker and NFS
      apt:
        name: "{{ item }}"
      with_items:
        - apt-transport-https
        - ca-certificates
        - python-pip
        - curl
        - nfs-common
        - zsh

    - name: Mount NAS directories
      mount:
        path: "{{ item.mountpoint }}"
        src: "{{ item.nasserver }}:{{ item.naspath }}"
        fstype: nfs
        opts: rw,soft
        dump: 0
        passno: 0
        state: mounted
      with_items:
        - mountpoint: /buildteam
          nasserver: cnt-s231.sc.couchbase.com
          naspath: /data/buildteam

    - name: Add docker key
      shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add docker apt repository
      shell: >
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes

    - name: Install docker-py
      pip:
        name: docker-py
        version: 1.9.0

    - name: Add couchbase user to docker group
      user:
        name: couchbase
        group: docker
        append: yes

    - name: Create docker systemd drop-in directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: 0755

    - name: Create docker systemd drop-in config file
      copy:
        src: docker-service.conf
        dest: /etc/systemd/system/docker.service.d/docker-service.conf
        backup: yes

    - name: Restart docker systemd service
      systemd:
        daemon_reload: yes
        name: docker
        state: restarted

