version: '3.7'

# Suggested deployment command:
#   docker --host mega4-swarm.build.couchbase.com stack deploy -c docker-registry.yaml docker
# All services, networks, etc. will then get an "docker_" prefix,
# eg. "docker_registry"

services:
  registry:
    deploy:
      replicas: 1
    image: registry:2
    ports:
      - 443:443
    configs:
      - source: docker_registry_config_20200212
        target: /etc/docker/registry/config.yml
        mode: 0664
    secrets:
      - source: buildhub.crt
      - source: buildhub.key
    volumes:
      - type: bind
        source: /buildteam/docker/registry
        target: /var/lib/registry
    networks:
      registry:

  registry-cleanup:
    deploy:
      replicas: 0
      restart_policy:
        condition: none
    image: registry:2
    entrypoint:
      - /entrypoint.sh
      - garbage-collect
      - /etc/docker/registry/config.yml
    configs:
      - source: docker_registry_config_20200212
        target: /etc/docker/registry/config.yml
        mode: 0664
    volumes:
      - type: bind
        source: /buildteam/docker/registry
        target: /var/lib/registry
    networks:
      registry:

  frontend:
    deploy:
      replicas: 1
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8010:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 443
      ENV_DOCKER_REGISTRY_USE_SSL: 1
      ENV_REGISTRY_PROXY_FQDN: build-docker.couchbase.com
      ENV_REGISTRY_PROXY_PORT: 443
    networks:
      registry:

  joxit:
    deploy:
      replicas: 1
    image: joxit/docker-registry-ui:static
    ports:
      - 8020:80
    environment:
      REGISTRY_URL: https://build-docker.couchbase.com:443
      DELETE_IMAGES: "true"
      REGISTRY_TITLE: "Couchbase Build Registry"
    networks:
      registry:

configs:
  docker_registry_config_20200212:
    file: conf/registry-config.yml

secrets:
  buildhub.crt:
    external: true
  buildhub.key:
    external: true

networks:
  registry: