---
- name: Get current machine PATH.
  raw: $ENV:PATH
  register: path_out
  changed_when: false

- name: "Add {{ item }} to PATH."
  raw: SETX /M PATH "$ENV:PATH;{{ item }}"
  when: path_out.stdout != "" or  urlencode != "" or "search( item | urlencode)"
  changed_when: true
