---
- hosts: all

  tasks:

    - name: "Install Python 3"
      win_chocolatey:
        name: python3
        version: 3.6.6
      tags: python3

    - name: Install tools
      win_chocolatey:
        name: "{{ item }}"
        allow_empty_checksums: "yes"
      with_items:
        - kb2919355
        - kb2999226
        - kb2919442
        - 7zip.commandline
        - awstools.powershell
        - cmake
        - curl
        - docfx
        - git
        - jdk8
        - ninja
        - wget
        - wixtoolset


    - name: Install Visual Studio Code
      win_chocolatey:
        name: "visualstudiocode"
        ignore_dependencies: yes

    - name: Create directory structure
      win_file:
        path: C:\bin
        state: directory

    - name: "Install repo"
      win_get_url:
        url: "https://raw.githubusercontent.com/esrlabs/git-repo/stable/repo"
        dest: 'C:\bin\repo'
      tags:
        - repo

    # This repo.exe was built using the "py-wrapper" source code here:
    # https://github.com/couchbase/build-tools/tree/master/py-wrapper
    - name: "Install repo wrapper"
      win_copy:
        src: repo.exe
        dest: 'C:\bin\'

    # Due to a silly bug in ESRlabs' Repo port, git's core.pager setting MUST
    # be set, and moreover it MUST be set to a command that exists as a .exe.
    # more is actually "more.com", and while setting core.pager to "more.com"
    # works well from a command prompt, it throws a Python error when invoked
    # via Jenkins "Gerrit Repo" source-control plugin. So, we use MSYS's
    # "cat.exe", which requires that we copy both that file and a few MSYS
    # DLLs onto the PATH.
    - name: "Copy MSYS tools to C:\\bin for repo"
      win_copy:
        src: 'C:\Program Files\Git\usr\bin\{{ item }}'
        dest: 'C:\bin\'
        remote_src: yes
      loop:
        - cat.exe
        - msys-2.0.dll
        - msys-iconv-2.dll
        - msys-intl-8.dll
      tags:
        - repo

    - name: Copy .gitconfig file
      win_copy:
        src: "gitconfig"
        dest: C:\Users\{{ ansible_user }}\.gitconfig
      tags:
        - repo

    - name: Get Current PATH
      raw: $ENV:PATH
      register: path_out

    - debug: var=path_out.stdout_lines

    - name: Add tools to PATH.
      win_path:
          elements:
          - C:\bin
          - C:\Program Files\CMake\bin
          - C:\Program Files\git\cmd
          - C:\Program Files (x86)\WiX Toolset v3.11\bin

    - name: Install OpenSSH (for Jenkins)
      script: openssh.ps1

    - name: Create SSH directory
      win_file:
        path: C:\Users\{{ ansible_user }}\.ssh
        state: directory

    - name: Copy SSH config files
      win_copy:
        src: "./ssh/{{ item }}"
        dest: C:\Users\{{ ansible_user }}\.ssh\{{ item }}
      with_items:
        - authorized_keys
        - buildbot_id_dsa
        - config
        - environment
        - id_rsa
        - known_hosts

    - name: Enable Remote Desktop
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present

    - name: Open Remote Desktop in firewall
      win_firewall_rule:
        name: "remote desktop"
        enable: yes
        state: present
        localport: 3389
        action: allow
        direction: in
        protocol: TCP
        force: true

    - name: Exclude Jenkins from windows antivirus
      win_shell: Add-MpPreference -ExclusionPath "C:\Jenkins"

    #base vs2017 install role from ../../roles/vs2017_mobile/
    - name: install vs2017_mobile
      include_role:
        name: "vs2017_mobile"
      vars:
        PRODUCT: "couchbase-lite-core"
