---
- hosts: all

  vars:
    kbs:
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: clearcompressionflag.exe
      - guid: D/6/0/D60ED3E0-93A5-4505-8F6A-8D0A5DA16C8A
        filename: Windows8.1-KB2919442-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2919355-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2932046-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2959977-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2937592-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2938439-x64.msu
      - guid: 2/5/6/256CCCFB-5341-4A8D-A277-8A81B21A1E35
        filename: Windows8.1-KB2934018-x64.msu
      - guid: D/1/3/D13E3150-3BB2-4B22-9D8A-47EE2D609FFF
        filename: Windows8.1-KB2999226-x64.msu

  tasks:

    # Needed for WiX Toolset
    - name: "Enable .NET Framework 3.5"
      win_feature:
        name: "NET-Framework-Core"
        state: present

    # Have to do this first so that the later python2 ends up
    # earlier on PATH (ie, we want python2 to be default)
    - name: "Install Python 3"
      win_chocolatey:
        name: python3
        version: 3.6.6
      tags: python3

    - name: "Provide python3 alias"
      win_shell: copy C:\Python36\python.exe C:\Python36\python3.exe
      args:
        creates: C:\Python36\python3.exe
      tags: python3

    - name: "Provide python3.6 alias"
      win_shell: copy C:\Python36\python.exe C:\Python36\python3.6.exe
      args:
        creates: C:\Python36\python3.6.exe
      tags: python3

    - name: "Install Python 2"
      win_chocolatey:
        name: python2
      tags: python2

    - name: "Install tools"
      win_chocolatey:
        name: "{{ item }}"
        allow_empty_checksums: "yes"
      with_items:
        - git
        - cmake
        - curl
        - nasm
        - ninja
        - MinGW
        - vcpython27
        - ruby
        - wixtoolset
        - 7zip.commandline
        - jdk8
        - maven
        - activeperl
        - googlechrome
        - insted
        - pandoc

    - name: "Install python paramiko module"
      win_command: C:\Python27\Scripts\pip.exe install paramiko
      tags: python2

    # Code depends on .NET Framework 4.5.2 (chocolatey package "dotnet4.5.2"),
    # but that package fails to install via Ansible due to silly limitations
    # in WinRM (see also: all the nonsense in install-kb.yml). However, the
    # framework is actually installed by default on Server 2012R2, so there's
    # no need to install it. So we just tell chocolatey to skip dependencies.
    - name: "Install Visual Studio Code"
      win_chocolatey:
        name: "visualstudiocode"
        ignore_dependencies: yes

    - name: "Download py2exe"
      win_get_url:
        url: https://iweb.dl.sourceforge.net/project/py2exe/py2exe/0.6.9/py2exe-0.6.9.win64-py2.7.amd64.exe
        dest: C:\py2exe.exe

    - name: "Install py2exe"
      raw: 'easy_install C:\py2exe.exe'

    - name: Create bin directory
      win_file:
        path: "C:\\bin"
        state: directory

    - name: "Install repo"
      win_copy:
        src: "repo.exe"
        dest: "C:\\bin\\repo.exe"

    - name: "Download patch_via_gerrit"
      win_get_url:
        url: http://latestbuilds.service.couchbase.com/builds/latestbuilds/python_tools/patch_via_gerrit/1.0.0/8/windows_msvc2015/patch_via_gerrit.exe
        dest: C:\bin\patch_via_gerrit.exe

    - name: Add tools to PATH.
      include: extend-path.yml
      with_items:
        - C:\bin
        - C:\Program Files\CMake\bin
        - C:\Program Files\git\cmd
        - C:\Program Files\NASM
        - C:\Program Files (x86)\WiX Toolset v3.11\bin


# Next steps are all about installing Visual Studio

    - name: Install pre-req Windows updates
      include: install-kb.yml
      with_items: "{{ kbs }}"
      tags: kbs

    - name: Copy unattended.xml
      win_copy:
        src: "vs-unattended.xml"
        dest: "C:\\vs-unattended.xml"

    - name: Install Visual Studio Professional 2015 (takes a long time)
      script: install-vs.ps1 -vskey {{ vskey }}
      register: choco_output
      changed_when: not "already installed" in choco_output.stdout
      failed_when: false

    - name: Reboot Windows if necessary
      win_reboot:
        reboot_timeout_sec: 3600
      when: '"reboot is necessary" in choco_output.stdout'

    - name: Download older VS CRT Merge Modules
      win_get_url:
        url: "{{ item.url }}"
        dest: "C:\\Program Files (x86)\\Common Files\\Merge Modules\\{{ item.filename }}"
        force: no
      with_items:
        - url: http://downloads.build.couchbase.com/winbits/Microsoft_VC100_CRT_x64.msm
          filename: Microsoft_VC100_CRT_x64.msm
        - url: http://downloads.build.couchbase.com/winbits/Microsoft_VC120_CRT_x64.msm
          filename: Microsoft_VC120_CRT_x64.msm

# Do OpenSSH last so the service has the latest version of the path

    - name: Install OpenSSH (for Jenkins)
      script: openssh.ps1

# Some of these files contain private information, so they're not all in git.

    - name: Copy SSH config files
      win_copy:
        src: "./ssh/{{ item }}"
        dest: C:\Users\Administrator\.ssh\{{ item }}
      with_items:
        - authorized_keys
        - buildbot_id_dsa
        - config
        - environment
        - id_rsa
        - known_hosts

    - name: "Enable Remote Desktop"
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present

    - name: "Open Remote Desktop in firewall"
      win_firewall_rule:
        name: "remote desktop"
        enable: yes
        state: present
        localport: 3389
        action: allow
        direction: in
        protocol: TCP

