---
- hosts: all
  gather_facts: False

  vars:
    ccache_dir: /home/couchbase/slaves/{{ slave_name }}_ccache
    restart_cmd: >-
      /home/couchbase/build-infra/docker-scripts/restart_jenkinsdocker.py
      --no-std-mounts
      {{ docker_image }}
      {{ slave_name }}
      {{ port | default('2222') }}
      cv.jenkins.couchbase.com
      --ccache-dir {{ ccache_dir }}

  tasks:
    - name: Update build-infra repo
      git:
        repo: git://github.com/couchbase/build-infra
        dest: /home/couchbase/build-infra

    - name: Synchronize jenkinsdocker-ssh
      synchronize:
        src: /home/couchbase/jenkinsdocker-ssh/
        dest: /home/couchbase/jenkinsdocker-ssh/
        archive: yes
        delete: yes

    - name: Ensure cronscript exists
      file:
        path: /home/couchbase/cronscript
        state: touch

    - name: Add doc comment to cronscript
      lineinfile:
        path: /home/couchbase/cronscript
        regexp: "NOTICE"
        line: "# NOTICE: Automatically generated by build-infra/ansible/linux/cv"

    - name: "Create CCache directory"
      file:
        name: "{{ ccache_dir }}"
        state: directory

    - name: "Get hostname"
      shell: "hostname"
      register: hostname

    - name: "Create CCache configuration"
      copy:
        dest: "{{ ccache_dir }}/ccache.conf"
        content: "{{'max_size=50G\n' if 'large' in hostname.stdout else 'max_size=8G\n'}}"
        mode: 0644

    - name: "Pull latest CV container"
      shell: docker pull "{{ docker_image }}"

    - name: "Who am I?"
      shell: whoami

    - name: "Where am I?"
      shell: hostname

    - name: "Restart CV container"
      shell: "{{ restart_cmd }}"

    - name: "Take ownership of ~/slaves"
      file:
        path: /home/couchbase/slaves/{{ slave_name }}
        owner: couchbase
        group: docker
      become: true

    - name: "Append to disk-check cron script"
      lineinfile:
        path: /home/couchbase/cronscript
        regexp: "{{ slave_name }}"
        line: "/home/couchbase/build-infra/docker-scripts/run_if_disk_full.sh 85 {{ restart_cmd }}"

    - name: "Remove unused docker images and data"
      shell: "docker system prune --all --force"

    - name: Add disk-check cron job
      cron:
        name: "check diskspace"
        minute: "0"
        job: "/bin/bash /home/couchbase/cronscript"

    - name: Add public SSH keys for easy access
      copy:
        src: authorized_keys
        dest: /home/couchbase/.ssh
        mode: 0600
