version: '3.5'

# Suggested deployment command:
#  docker --host sdk-swarm.build.couchbase.com stack deploy -c sdk-jenkins.yaml sdk
# All services, networks, etc. will then get an "sdk_" prefix,
# eg. "sdk_jenkins"

services:

  # sdk.jenkins.couchbase.com
  jenkins:
    image: jenkins/jenkins:2.219
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /buildteam/jenkins/sdk-jenkins-home
        target: /var/jenkins_home
    secrets:
      - source: buildbot_id_dsa
        target: /var/jenkins_home/.ssh/buildbot_id_dsa
        uid: '1000'
        gid: '1000'
        mode: 0400
    networks:
      - jenkins

# See http://www.technowise.in/2016/10/fix-no-valid-crumb-was-included-in.html
# and https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Nginx
# for the reason behind -Dhudson.security.csrf.requestfield
    environment:
      - "JAVA_OPTS=-Dhudson.security.csrf.requestfield=Jenkins-Crumb"

secrets:
  buildbot_id_dsa:
    external: true

networks:
  jenkins:
